
import React from 'react';
import { 
  Building2, 
  Zap, 
  Flame, 
  FileText, 
  HeartPulse, 
  ShoppingBasket, 
  Bot,
  Store
} from 'lucide-react';
import { ServiceInfo, ServiceType, Language } from './types';

export const DEPARTMENTS = [
  { id: ServiceType.GRAMPANCHAYAT, label: "Gram Panchayat" },
  { id: ServiceType.CHAVDI, label: "E-Chavdi / Revenue" },
  { id: ServiceType.ELECTRICITY, label: "Electricity (MSEB)" },
  { id: ServiceType.GAS, label: "Gas Agency" },
  { id: ServiceType.HEALTH, label: "Public Health (PHC)" },
  { id: ServiceType.MARKET, label: "Agricultural Mandi" },
  { id: ServiceType.BUSINESS, label: "Local Business Directory" }
];

export const INDIA_LOCATIONS = {
  states: [
    "Maharashtra", "Gujarat", "Karnataka", "Rajasthan", "Uttar Pradesh", "Delhi", "Tamil Nadu", "Kerala"
  ],
  districts: {
    "Maharashtra": [
      "Ahmednagar", "Akola", "Amravati", "Aurangabad", "Beed", "Bhandara", "Buldhana", 
      "Chandrapur", "Dhule", "Gadchiroli", "Gondia", "Hingoli", "Jalgaon", "Jalna", 
      "Kolhapur", "Latur", "Mumbai City", "Mumbai Suburban", "Nagpur", "Nanded", 
      "Nandurbar", "Nashik", "Osmanabad", "Palghar", "Parbhani", "Pune", "Raigad", 
      "Ratnagiri", "Sangli", "Satara", "Sindhudurg", "Solapur", "Thane", "Wardha", "Washim", "Yavatmal"
    ],
    "Gujarat": ["Ahmedabad", "Amreli", "Anand", "Aravalli", "Banaskantha", "Bharuch", "Bhavnagar", "Botad", "Gandhinagar", "Jamnagar", "Junagadh", "Kutch", "Mehsana", "Morbi", "Narmada", "Navsari", "Panchmahal", "Patan", "Porbandar", "Rajkot", "Surat", "Vadodara", "Valsad"],
    "Karnataka": ["Bagalkot", "Ballari", "Belagavi", "Bengaluru Rural", "Bengaluru Urban", "Bidar", "Chamarajanagar", "Chikkaballapur", "Chikkamagaluru", "Chitradurga", "Dakshina Kannada", "Davanagere", "Dharwad", "Gadag", "Hassan", "Haveri", "Kalaburagi", "Kodagu", "Kolar", "Koppal", "Mandya", "Mysuru", "Raichur", "Ramanagara", "Shivamogga", "Tumakuru", "Udupi", "Uttara Kannada", "Vijayapura", "Yadgir"]
  },
  subDistricts: {
    "Pune": ["Haveli", "Mulshi", "Shirur", "Maval", "Bhor", "Daund", "Indapur", "Junnar", "Khed", "Ambegaon", "Purandar", "Velhe", "Baramati"],
    "Nashik": ["Nashik", "Sinnar", "Igatpuri", "Dindori", "Niphad", "Yeola", "Nandgaon", "Chandwad", "Kalwan", "Baglan", "Surgana", "Peint", "Trimbakeshwar", "Deola"],
    "Nagpur": ["Nagpur", "Kamptee", "Hingna", "Katol", "Kalameshwar", "Savner", "Ramtek", "Mauda", "Umred", "Bhiwapur", "Kuhi", "Narkhed"],
    "Aurangabad": ["Aurangabad", "Kannad", "Soegaon", "Sillod", "Phulambri", "Khultabad", "Vaijapur", "Gangapur", "Paithan"],
    "Ahmednagar": ["Ahmednagar", "Rahuri", "Shrirampur", "Sangamner", "Kopargaon", "Akole", "Nevasa", "Shevgaon", "Pathardi", "Parner", "Karjat", "Jamkhed", "Shrigonda"],
    "Satara": ["Satara", "Karad", "Wai", "Mahabaleshwar", "Phaltan", "Maan", "Khatav", "Koregaon", "Patan", "Jawali", "Khandala"],
    "Solapur": ["Solapur North", "Solapur South", "Barshi", "Akkalkot", "Mohol", "Madha", "Karmala", "Pandharpur", "Sangola", "Malshiras", "Mangalwedhe"],
    "Thane": ["Thane", "Kalyan", "Murbad", "Bhiwandi", "Shahapur", "Ulhasnagar", "Ambarnath"],
    "Raigad": ["Alibag", "Pen", "Murud", "Panvel", "Uran", "Karjat", "Khalapur", "Mangaon", "Roha", "Tala", "Mahad", "Poladpur", "Shrivardhan", "Mhasala"],
    "Ratnagiri": ["Ratnagiri", "Sangameshwar", "Lanja", "Rajapur", "Chiplun", "Guhagar", "Khed", "Dapoli", "Mandangad"],
    "Kolhapur": ["Karveer", "Panhala", "Shahuwadi", "Kagal", "Gadhinglaj", "Shirol", "Hatkanangale", "Radhanagari", "Gaganbawada", "Bhudargad", "Ajara", "Chandgad"],
    "Nanded": ["Nanded", "Mudkhed", "Ardhapur", "Bhokar", "Umri", "Loha", "Kandhar", "Naigaon", "Biloli", "Dharmabad", "Mukhed", "Hadgaon", "Himayatnagar", "Mahoor", "Degloor"],
    "Jalgaon": ["Jalgaon", "Bhusawal", "Raver", "Muktainagar", "Bodwad", "Yawal", "Chopda", "Amalner", "Parola", "Erandol", "Pachora", "Bhadgaon", "Chalisgaon", "Jamner", "Dharangaon"],
    "Sangli": ["Miraj", "Jat", "Khanapur", "Walwa", "Tasgaon", "Shirala", "Atpadi", "Kavathe Mahankal", "Palus", "Kadegaon"],
    "Latur": ["Latur", "Udgir", "Ahmedpur", "Nilanga", "Ausa", "Chakur", "Jalkot", "Shirur Anantpal", "Deoni", "Renapur"],
    "Beed": ["Beed", "Ashti", "Patoda", "Shirur Kasar", "Georai", "Majalgaon", "Wadwani", "Kaij", "Dharur", "Parli", "Ambejogai"],
    "Amravati": ["Amravati", "Bhatkuli", "Nandgaon Khandeshwar", "Dharni", "Chikhaldara", "Achalpur", "Chandur Bazar", "Morshi", "Warud", "Daryapur", "Anjangaon Surji", "Chandur Railway", "Dhamangaon Railway", "Teosa"],
    "Akola": ["Akola", "Akot", "Telhara", "Balapur", "Patur", "Murtijapur", "Barshitakli"],
    "Buldhana": ["Buldhana", "Chikhli", "Deulgaon Raja", "Jalgaon Jamod", "Sangrampur", "Malkapur", "Motala", "Nandura", "Khamgaon", "Shegaon", "Mehkar", "Sindkhed Raja", "Lonar"],
    "Ahmedabad": ["Ahmedabad City", "Daskroi", "Sanand", "Bavla", "Dholka", "Viramgam", "Mandal", "Detroj-Rampura", "Dhandhuka", "Ranpur", "Barwala"],
    "Bengaluru Urban": ["Bengaluru North", "Bengaluru South", "Bengaluru East", "Anekal"],
    "Bhandara": ["Bhandara", "Tumsar", "Pauni", "Mohadi", "Sakoli", "Lakhani", "Lakhandur"],
    "Chandrapur": ["Chandrapur", "Bhadravati", "Warora", "Chimur", "Nagbhir", "Brahmapuri", "Sindewahi", "Mul", "Sawali", "Gondpipri", "Korpana", "Rajura", "Ballarpur", "Pombhurna", "Jiwati"],
    "Dhule": ["Dhule", "Sakri", "Sindkhede", "Shirpur"],
    "Gadchiroli": ["Gadchiroli", "Dhanora", "Chamorshi", "Mulchera", "Aheri", "Sironcha", "Etapalli", "Bhamragad", "Kurkheda", "Armori", "Korchi", "Desaiganj"],
    "Gondia": ["Gondia", "Tirora", "Goregaon", "Arjuni Morgaon", "Amgaon", "Salekasa", "Sadak Arjuni", "Deori"],
    "Hingoli": ["Hingoli", "Kalnuri", "Sengon", "Basmath", "Aundha Nagnath"],
    "Jalna": ["Jalna", "Bhokardan", "Jafrabad", "Badnapur", "Ambad", "Ghansawangi", "Partur", "Mantha"],
    "Nandurbar": ["Nandurbar", "Navapur", "Shahada", "Taloda", "Akkalkuwa", "Akrani"],
    "Osmanabad": ["Osmanabad", "Tuljapur", "Umarga", "Lohara", "Kalamb", "Bhum", "Paranda", "Washi"],
    "Palghar": ["Palghar", "Vasai", "Dahanu", "Talasari", "Jawhar", "Mokhada", "Wada", "Vikramgad"],
    "Parbhani": ["Parbhani", "Jintur", "Sailu", "Manwath", "Pathri", "Sonpeth", "Gangakhed", "Palam", "Purna"],
    "Sindhudurg": ["Sawantwadi", "Kudal", "Vengurla", "Malvan", "Kankavli", "Devgad", "Vaibhavwadi", "Dodamarg"],
    "Wardha": ["Wardha", "Seloo", "Arvi", "Ashti", "Karanja", "Hinganghat", "Samudrapur", "Deoli"],
    "Washim": ["Washim", "Risod", "Malegaon", "Mangrulpir", "Karanja", "Manora"],
    "Yavatmal": ["Yavatmal", "Babulgaon", "Kalamb", "Darwha", "Digras", "Arni", "Umarkhed", "Hadgaon", "Mahagaon", "Pusad", "Wani", "Maregaon", "Zari Jamani", "Kelapur", "Ghatanji", "Ralegaon"]
  },
  "villages": {
    "Haveli": ["Sukhawadi", "Hadapsar", "Loni Kalbhor", "Wagholi", "Kharadi", "Manjari", "Dhayari", "Nanded", "Shivane", "Uruli Kanchan", "Theur", "Bakori", "Kadamwak Vasti", "Kunjirwadi", "Sortapwadi", "Naigaon", "Loni-Kalbhor", "Phursungi"],
    "Mulshi": ["Hinjewadi", "Pirangut", "Bhugaon", "Bavdhan", "Paud", "Lavasa", "Male", "Mutha", "Kashig", "Kothurne", "Nande", "Sus", "Marunji", "Maan", "Gherane", "Kule", "Rihe"],
    "Shirur": ["Shirur", "Shikrapur", "Sanamwadi", "Koregaon Bhima", "Pabal", "Talegaon Dhamdhere", "Nhavare", "Kanhur Mesai", "Ranjangaon Ganpati", "Kardelwadi", "Nimgaon Mhalungi"],
    "Maval": ["Lonavala", "Khandala", "Talegaon Dabhade", "Kamshet", "Kanhe", "Vadgaon", "Malavli", "Karla", "Kusgaon", "Pimpri", "Sate"],
    "Bhor": ["Bhor", "Nasrapur", "Kapurhol", "Kikvi", "Rajgad", "Sangvi", "Nigade", "Kenjal", "Wing", "Ambavade"],
    "Daund": ["Daund", "Patas", "Kurkumbh", "Yavat", "Kedgaon", "Kashti", "Varvand", "Khor", "Rahu", "Gopalwadi"],
    "Indapur": ["Indapur", "Bhigwan", "Bawada", "Nimgaon Ketki", "Anthurne", "Lasurne", "Kalas", "Shetphal", "Loni Devkar"],
    "Junnar": ["Junnar", "Otur", "Narayangaon", "Alephata", "Belhe", "Aptale", "Ghodegaon", "Rajur", "Dingore"],
    "Khed": ["Chakan", "Rajgurunagar", "Alandi", "Mahalunge", "Khed City", "Pait", "Shel-Pimpalgaon", "Koye", "Waki"],
    "Ambegaon": ["Manchar", "Ghodegaon", "Pargaon", "Nirud", "Shinoli", "Loni", "Walunj", "Kalamb"],
    "Purandar": ["Saswad", "Jejuri", "Neera", "Walha", "Pimpale", "Diva", "Garade", "Kumbharvalan"],
    "Velhe": ["Velhe", "Panshet", "Gunjavane", "Margasani", "Pasali", "Kuran", "Ambavane"],
    "Nagpur": ["Nagpur City", "Hudkeshwar", "Besa", "Beltarodi", "Wadi", "Digdoh", "Nildoh", "Parsodi"],
    "Kamptee": ["Kamptee City", "Kanhan", "Yerkheda", "Bhilgaon", "Gumthala", "Mahadula"],
    "Hingna": ["Hingna", "Wanadongri", "Raipur", "Mandwa", "Sukali", "Takalghat"],
    "Aurangabad": ["Aurangabad City", "Waluj", "Bajaj Nagar", "Chitegaon", "Pandharpur", "Tisgaon", "Maliwada"],
    "Kannad": ["Kannad City", "Pishore", "Chapaner", "Nagad", "Amba"],
    "Paithan": ["Paithan City", "Bidkin", "Dhupkhed", "Mudhalwadi", "Pachod"],
    "Ahmednagar": ["Ahmednagar City", "Kedgaon", "Burudgaon", "Nimbodi", "Nagapur", "Vilad Ghat"],
    "Rahuri": ["Rahuri City", "Vambori", "Deolali Pravara", "Taklibhan", "Guhar"],
    "Sangamner": ["Sangamner City", "Ashwi", "Loni", "Sakur", "Talegaon Digar"],
    "Satara": ["Satara City", "Kodoli", "Khed", "Wadhe", "Limb", "Padali"],
    "Karad": ["Karad City", "Ogalewadi", "Malkapur", "Umbraj", "Kole", "Masur"],
    "Wai": ["Wai City", "Panchgani", "Bhuinj", "Surur", "Dhom"],
    "Solapur North": ["Solapur City", "Kegaon", "Bale", "Haglur", "Degaon"],
    "Solapur South": ["Mandrup", "Vairag", "Kumbhari", "Hotgi", "Valsang"],
    "Pandharpur": ["Pandharpur City", "Bhalwani", "Karkamb", "Shetphal", "Wakhari", "Kasegaon", "Tandulwadi", "Bhandishegaon"],
    "Barshi": ["Barshi City", "Vairag", "Pangri", "Gaudgaon", "Kari"],
    "Akkalkot": ["Akkalkot City", "Maindargi", "Dudhani", "Chapalgaon", "Wagdari"],
    "Mohol": ["Mohol City", "Kurul", "Kamti", "Shetphal", "Penur"],
    "Madha": ["Madha City", "Kurduwadi", "Tembhurni", "Modnimb", "Shetphal"],
    "Phaltan": ["Phaltan City", "Taradgaon", "Sakharwadi", "Barad", "Vathar"],
    "Koregaon": ["Koregaon City", "Rahimatpur", "Kumthe", "Wathar", "Pimpode"],
    "Murbad": ["Murbad City", "Saralgaon", "Dhasai", "Tokawade", "Kudavali"],
    "Shahapur": ["Shahapur City", "Asangaon", "Vashind", "Dolkhamb", "Kasara"],
    "Pen": ["Pen City", "Jite", "Kamarly", "Dadara", "Vat"],
    "Karjat": ["Karjat City", "Neral", "Matheran", "Khandas", "Kashele"],
    "Mangaon": ["Mangaon City", "Nizampur", "Lonere", "Indapur", "Goregaon"],
    "Sangameshwar": ["Sangameshwar City", "Derukh", "Makhajan", "Phungus", "Tural"],
    "Rajapur": ["Rajapur City", "Nate", "Pachal", "Oni", "Jaitapur"],
    "Panhala": ["Panhala City", "Kodoli", "Bambavade", "Kotoli", "Kale"],
    "Kagal": ["Kagal City", "Murgud", "Bidri", "Kapshi", "Sangaon"],
    "Shirol": ["Shirol City", "Jaisingpur", "Kurundwad", "Nandani", "Dharangutti"],
    "Mudkhed": ["Mudkhed City", "Barad", "Mugdha", "Chikhalwadi"],
    "Bhokar": ["Bhokar City", "Kini", "Matul", "Lagul"],
    "Loha": ["Loha City", "Sonkhed", "Malakoli", "Kapra"],
    "Raver": ["Raver City", "Khanpur", "Waghoda", "Kharda"],
    "Chopda": ["Chopda City", "Adavad", "Hated", "Dhanora"],
    "Amalner": ["Amalner City", "Marwad", "Dahiwad", "Pali"],
    "Tasgaon": ["Tasgaon City", "Anjani", "Balgavade", "Bhilawadi", "Borgaon", "Chinchani", "Dahivadi", "Hatnur", "Kavathe", "Kundal", "Limb", "Manerajuri", "Nimani", "Ped", "Savarde", "Visapur", "Yeralewadi", "Yeral", "Kumathe"],
    "Atpadi": ["Atpadi City", "Dighanchi", "Nimbavade", "Palsi"],
    "Kadegaon": ["Kadegaon City", "Wangi", "Nerli", "Talsangi"],
    "Ahmedpur": ["Ahmedpur City", "Kingaon", "Shirur", "Hadolti"],
    "Nilanga": ["Nilanga City", "Aurad Shahajani", "Kasarsirsi", "Madansuri"],
    "Ausa": ["Ausa City", "Killari", "Lamjana", "Bhada"],
    "Ashti": ["Ashti City", "Kada", "Amalner", "Doithan"],
    "Georai": ["Georai City", "Umapur", "Chakala", "Madalmohi"],
    "Majalgaon": ["Majalgaon City", "Talkhed", "Nittur", "Pimpri"],
    "Morshi": ["Morshi City", "Hiwarkhed", "Rithpur", "Ner Pinglai"],
    "Warud": ["Warud City", "Shendurjana Ghat", "Benoda", "Loni"],
    "Daryapur": ["Daryapur City", "Yeoda", "Khallar", "Sanglud"],
    "Akot": ["Akot City", "Chohatta", "Hiwarkhed", "Adgaon"],
    "Telhara": ["Telhara City", "Hivarkhed", "Panchgavan", "Warwat"],
    "Chikhli": ["Chikhli City", "Amrapur", "Undri", "Eklara"],
    "Malkapur": ["Malkapur City", "Nandura", "Motala", "Wadner"],
    "Mehkar": ["Mehkar City", "Janephal", "Dongaon", "Loni"],
    "Thane": ["Thane City", "Majiwada", "Kopri", "Kalwa", "Mumbra", "Diva", "Kolshet", "Balkum", "Ghodbunder", "Waghbil"],
    "Kalyan": ["Kalyan City", "Dombivli", "Titwala", "Mohone", "Shahad", "Ambivli"],
    "Bhiwandi": ["Bhiwandi City", "Padgha", "Khoni", "Anjur", "Pise"],
    "Alibag": ["Alibag", "Revdanda", "Chaul", "Akshi", "Nagaon", "Kihim", "Vadavali", "Khandala"],
    "Panvel": ["Panvel City", "Kamothe", "Kalamboli", "Khandeshwar", "New Panvel", "Taloja", "Vichumbe", "Koproli", "Kharghar", "Ulwe", "Dronagiri", "Palaspe", "Shirdhon"],
    "Ratnagiri": ["Ratnagiri City", "Mirya", "Pawas", "Ganpatipule", "Malgund", "Shirgaon", "Nachane"],
    "Chiplun": ["Chiplun City", "Sawarde", "Kherdi", "Pophali", "Dhamandevi"],
    "Karveer": ["Kolhapur", "Uchgaon", "Gandhinagar", "Mudshingi", "Sarnobatwadi", "Vashi", "Shiroli", "Gokul Shirgaon"],
    "Hatkanangale": ["Ichalkaranji", "Hatkanangale", "Peth Vadgaon", "Rukadi", "Herle"],
    "Nanded": ["Nanded City", "Waghala", "Vishnupuri", "Tuppa", "CIDCO"],
    "Mukhed": ["Mukhed City", "Jahoor", "Barahali", "Ravi"],
    "Jalgaon": ["Jalgaon City", "Nashirabad", "Pimprala", "Mehrun", "Kusumba"],
    "Bhusawal": ["Bhusawal City", "Varangaon", "Kandari", "Sakegaon"],
    "Miraj": ["Arag", "Bedag", "Belanki", "Bolwad", "Erandoli", "Gundewadi", "Kalambi", "Kanadewadi", "Khanderajuri", "Lingnur", "Malgaon", "Mallewadi", "Mhaishal", "Nilji", "Salgare", "Siddhewadi", "Tanang", "Yerla", "Bisur", "Inam Dhamani", "Kavalapur", "Kharsing", "Kumthe", "Miraj Rural", "Nandra", "Padamale", "Patgaon", "Shipur", "Takari", "Vaddi", "Sangli City", "Kupwad"],
    "Walwa": ["Islampur", "Ashta", "Bahe", "Boregaon", "Chikurde", "Dhavali", "Hubli", "Kameri", "Kasegaon", "Kurundwad", "Narsingpur", "Peth", "Rethare", "Sakharale", "Shirgaon", "Tandulwadi", "Walwa Village", "Yede Nipani"],
    "Latur": ["Latur City", "Pakharsangvi", "Arvi", "Kanheri", "Harangul"],
    "Udgir": ["Udgir City", "Deoni", "Nalegaon", "Wadhwana"],
    "Beed": ["Beed City", "Nalwandi", "Pali", "Limba"],
    "Parli": ["Parli City", "Pangri", "Dharmapuri", "Sirala"],
    "Amravati": ["Amravati City", "Badnera", "Walgaon", "Loni", "Kathora"],
    "Achalpur": ["Paratwada", "Achalpur City", "Chandur Bazar", "Shirala"],
    "Akola": ["Akola City", "Shivani", "Malkapur", "Kharda", "Umri"],
    "Buldhana": ["Buldhana City", "Warwand", "Dhad", "Padli"],
    "Khamgaon": ["Khamgaon City", "Shegaon", "Pala", "Ganeshpur"],
    "default": ["Gaothan", "Ward No 1", "Ward No 2", "Station Area", "Market Yard", "Gram Panchayat Area", "Main Road", "Vikas Nagar", "Shivaji Chowk", "Adarsh Nagar", "Hanuman Mandir Area"]
  }
};

export const DICTIONARY: Record<string, Record<Language, string>> = {
  appName: { en: 'MyGaav', hi: 'मेरा गाँव', mr: 'माझे गाव' },
  welcome: { en: 'Welcome', hi: 'स्वागत है', mr: 'स्वागत आहे' },
  home: { en: 'Home', hi: 'होम', mr: 'मुख्यपृष्ठ' },
  tickets: { en: 'Tickets', hi: 'तिकीट', mr: 'तक्रार निवारण' },
  sahayak: { en: 'Sahayak', hi: 'सहायक', mr: 'सहाय्यक' },
  profile: { en: 'Profile', hi: 'प्रोफाइल', mr: 'प्रोफाइल' },
  about: { en: 'About', hi: 'जानकारी', mr: 'बद्दल' },
  logout: { en: 'Sign Out', hi: 'लॉग आउट', mr: 'बाहेर पडा' },
  askAi: { en: 'Ask AI Assistant', hi: 'AI सहायक से पूछें', mr: 'AI सहाय्यकाला विचारा' },
  typeQ: { en: 'Type your question...', hi: 'अपना प्रश्न लिखें...', mr: 'तुमचा प्रश्न लिहा...' },
  thinking: { en: 'Sahayak is thinking...', hi: 'सहायक सोच रहा है...', mr: 'सहाय्यक विचार करत आहे...' },
  recentNotices: { en: 'Recent Notices', hi: 'हालिया सूचनाएं', mr: 'नुकत्याच आलेल्या सूचना' },
  pendingBills: { en: 'Pending Bills', hi: 'बकाया बिल', mr: 'प्रलंबित बिले' },
  mainPortals: { en: 'Main Service Portals', hi: 'मुख्य सेवा पोर्टल', mr: 'मुख्य सेवा पोर्टल' },
  enterPortal: { en: 'Enter Portal', hi: 'पोर्टल में प्रवेश करें', mr: 'पोर्टल उघडा' },
  payNow: { en: 'Pay Now', hi: 'अभी भुगतान करें', mr: 'आता भरा' },
  payMonthlyBill: { en: 'Pay Monthly Bill', hi: 'मासिक बिल का भुगतान करें', mr: 'मासिक बिल भरा' },
  paymentPending: { en: 'Payment Pending', hi: 'भुगतान लंबित', mr: 'पेमेंट प्रलंबित' },
  activeAssessments: { en: 'Active Assessments', hi: 'सक्रिय आकलन', mr: 'सक्रिय मूल्यांकन' },
  recentSettlements: { en: 'Recent Settlements', hi: 'हालिया निपटान', mr: 'अलीकडील भरणा' },
  availablePortals: { en: 'Available Portals', hi: 'उपलब्ध पोर्टल', mr: 'उपलब्ध सेवा' },
  aiConsult: { en: 'AI Consultation', hi: 'AI परामर्श', mr: 'AI सल्ला' },
  needHelp: { en: 'Need Help?', hi: 'क्या आपको मदद चाहिए?', mr: 'मदत हवी आहे का?' },
  reportIssue: { en: 'Report Issue', hi: 'समस्या की रिपोर्ट करें', mr: 'तक्रार नोंदवा' },
  gramPanchayat: { en: 'Gram Panchayat', hi: 'ग्राम पंचायत', mr: 'ग्रामपंचायत' },
  electricity: { en: 'Electricity', hi: 'बिजली', mr: 'वीज' },
  gas: { en: 'Gas Services', hi: 'गैस सेवाएँ', mr: 'गॅस सेवा' },
  chavdi: { en: 'E-Chavdi', hi: 'ई-चावड़ी', mr: 'ई-चावडी' },
  officialVillageAnnouncement: { en: 'Official Village Announcement', hi: 'आधिकारिक गांव घोषणा', mr: 'अधिकृत ग्राम घोषणा' },
  acknowledge: { en: 'Acknowledge', hi: 'स्वीकार करें', mr: 'समजले' },
  allTaxesPaid: { en: 'All Taxes Paid', hi: 'सभी करों का भुगतान किया गया', mr: 'सर्व कर भरले गेले आहेत' },
  noPendingDues: { en: 'No Pending Dues', hi: 'कोई बकाया नहीं', mr: 'कोणतीही थकबाकी नाही' },
  taxInvoice: { en: 'Tax Invoice', hi: 'टैक्स इनवॉइस', mr: 'कर बीजक' },
  paymentReceipt: { en: 'Payment Receipt', hi: 'भुगतान रसीद', mr: 'पेमेंट पावती' },
  totalPaid: { en: 'Total Paid', hi: 'कुल भुगतान', mr: 'एकूण भरणा' },
  amountDue: { en: 'Amount Due', hi: 'बकाया राशि', mr: 'देय रक्कम' },
  residentPortal: { en: 'Resident Portal', hi: 'निवासी पोर्टल', mr: 'निवासी पोर्टल' },
  officerPortal: { en: 'Officer Portal', hi: 'अधिकारी पोर्टल', mr: 'अधिकारी पोर्टल' },
  fullName: { en: 'Full Name', hi: 'पूरा नाम', mr: 'पूर्ण नाव' },
  emailAddress: { en: 'Email Address', hi: 'ईमेल पता', mr: 'ईमेल पत्ता' },
  mobileNumber: { en: 'Mobile Number', hi: 'मोबाइल नंबर', mr: 'मोबाईल नंबर' },
  password: { en: 'Password', hi: 'पासवर्ड', mr: 'पासवर्ड' },
  createAccount: { en: 'Create Account', hi: 'खाता बनाएँ', mr: 'खाते तयार करा' },
  signInSecurely: { en: 'Sign In Securely', hi: 'सुरक्षित रूप से साइन इन करें', mr: 'सुरक्षितपणे लॉग इन करा' },
  alreadyHaveAccount: { en: 'Already have an account? Login', hi: 'क्या आपके पास पहले से खाता है? लॉगिन करें', mr: 'आधीच खाते आहे? लॉग इन करा' },
  dontHaveAccount: { en: "Don't have an account? Signup", hi: 'खाता नहीं है? साइन अप करें', mr: 'खाते नाही? साइन अप करा' },
  villageConnectivity: { en: 'Village Connectivity', hi: 'गांव कनेक्टिविटी', mr: 'ग्राम जोडणी' },
  state: { en: 'State', hi: 'राज्य', mr: 'राज्य' },
  district: { en: 'District', hi: 'जिला', mr: 'जिल्हा' },
  taluka: { en: 'Taluka', hi: 'तालुका', mr: 'तालुका' },
  village: { en: 'Village', hi: 'गांव', mr: 'गाव' },
  pincode: { en: 'Pincode', hi: 'पिनकोड', mr: 'पिनकोड' },
  physicalAddress: { en: 'Physical Address', hi: 'भौतिक पता', mr: 'राहण्याचा पत्ता' },
  gramPanchayatId: { en: 'Gram Panchayat ID', hi: 'ग्राम पंचायत आईडी', mr: 'ग्रामपंचायत आयडी' },
  electricityConsumerNo: { en: 'Electricity Consumer No', hi: 'बिजली उपभोक्ता संख्या', mr: 'वीज ग्राहक क्रमांक' },
  gasConsumerId: { en: 'Gas Consumer ID', hi: 'गैस उपभोक्ता आईडी', mr: 'गॅस ग्राहक आयडी' },
  chavdiAccountNo: { en: 'Chavdi Account No', hi: 'चावड़ी खाता संख्या', mr: 'चावडी खाते क्रमांक' },
  healthId: { en: 'Health ID / ABHA ID', hi: 'स्वास्थ्य आईडी / आभा आईडी', mr: 'आरोग्य आयडी / आभा आयडी' },
  selectDepartment: { en: 'Select Your Department', hi: 'अपने विभाग का चयन करें', mr: 'आपला विभाग निवडा' },
  moreServices: { en: 'More Services', hi: 'अधिक सेवाएँ', mr: 'अधिक सेवा' },
  lessServices: { en: 'Show Less', hi: 'कम दिखाएं', mr: 'कमी दाखवा' },
  liveWeather: { en: 'Live Weather', hi: 'लाइव मौसम', mr: 'थेट हवामान' },
  addVillage: { en: 'Add Village', hi: 'गांव जोड़ें', mr: 'गाव जोडा' },
  trackWeather: { en: 'Track weather for another gaav', hi: 'दूसरे गांव के मौसम पर नज़र रखें', mr: 'दुसऱ्या गावाच्या हवामानाचा मागोवा घ्या' },
  enterVillageName: { en: 'Enter Village Name...', hi: 'गांव का नाम दर्ज करें...', mr: 'गावाचे नाव टाका...' },
  cancel: { en: 'Cancel', hi: 'रद्द करें', mr: 'रद्द करा' },
  add: { en: 'Add', hi: 'जोड़ें', mr: 'जोडा' },
  forecast3Day: { en: '3-Day Forecast', hi: '3-दिन का पूर्वानुमान', mr: '३-दिवसांचा अंदाज' },
  humidity: { en: 'Humidity', hi: 'नमी', mr: 'आद्रता' },
  wind: { en: 'Wind', hi: 'हवा', mr: 'वारा' },
  feelsLike: { en: 'Feels Like', hi: 'महसूस होता है', mr: 'जाणवते' },
  loadingWeather: { en: 'Loading Weather...', hi: 'मौसम लोड हो रहा है...', mr: 'हवामान लोड होत आहे...' },
  retry: { en: 'Retry', hi: 'पुनः प्रयास करें', mr: 'पुन्हा प्रयत्न करा' },
  liveUpdates: { en: 'Live Updates', hi: 'लाइव अपडेट', mr: 'थेट अपडेट' },
  weatherAlert: { en: 'Weather Alert', hi: 'मौसम की चेतावनी', mr: 'हवामान इशारा' },
  localMarketplace: { en: 'Local Marketplace', hi: 'स्थानीय बाजार', mr: 'स्थानिक बाजार' },
  villageBusinessHub: { en: 'Village Business Hub', hi: 'गांव व्यवसाय केंद्र', mr: 'ग्राम व्यवसाय केंद्र' },
  exploreLocalServices: { en: 'Explore and support local services', hi: 'स्थानीय सेवाओं का अन्वेषण और समर्थन करें', mr: 'स्थानिक सेवांचा शोध घ्या आणि त्यांना पाठिंबा द्या' },
  searchShops: { en: 'Search shops, services...', hi: 'दुकानें, सेवाएँ खोजें...', mr: 'दुकाने, सेवा शोधा...' },
  all: { en: 'All', hi: 'सब', mr: 'सर्व' },
  noBusinesses: { en: 'No matching businesses found', hi: 'कोई मेल खाने वाला व्यवसाय नहीं मिला', mr: 'कोणतेही जुळणारे व्यवसाय आढळले नाहीत' },
  owner: { en: 'Owner', hi: 'मालिक', mr: 'मालक' },
  hours: { en: 'Hours', hi: 'घंटे', mr: 'वेळ' },
  contact: { en: 'Contact', hi: 'संपर्क', mr: 'संपर्क' },
  callNow: { en: 'Call Now', hi: 'अभी कॉल करें', mr: 'आता कॉल करा' },
  registerBusiness: { en: 'Register Your Business', hi: 'अपना व्यवसाय पंजीकृत करें', mr: 'तुमच्या व्यवसायाची नोंदणी करा' },
  getListed: { en: 'Get listed in the village directory', hi: 'गांव निर्देशिका में सूचीबद्ध हों', mr: 'ग्राम निर्देशिकेत नाव नोंदवा' },
  businessIssues: { en: 'Business directory issues', hi: 'व्यवसाय निर्देशिका समस्याएँ', mr: 'व्यवसाय निर्देशिका समस्या' },
  newListing: { en: 'New Local Listing', hi: 'नई स्थानीय सूची', mr: 'नवीन स्थानिक सूची' },
  businessName: { en: 'Business Name', hi: 'व्यवसाय का नाम', mr: 'व्यवसायाचे नाव' },
  shopName: { en: 'Shop Name', hi: 'दुकान का नाम', mr: 'दुकानाचे नाव' },
  category: { en: 'Category', hi: 'श्रेणी', mr: 'वर्ग' },
  ownerName: { en: 'Owner Name', hi: 'मालिक का नाम', mr: 'मालकाचे नाव' },
  operatingHours: { en: 'Operating Hours', hi: 'संचालन के घंटे', mr: 'कामाची वेळ' },
  description: { en: 'Description', hi: 'विवरण', mr: 'वर्णन' },
  uploadProof: { en: 'Upload Proof Document', hi: 'प्रमाण दस्तावेज अपलोड करें', mr: 'पुरावा दस्तऐवज अपलोड करा' },
  processRequest: { en: 'Process Request', hi: 'अनुरोध संसाधित करें', mr: 'विनंतीवर प्रक्रिया करा' },
  citizenRequest: { en: 'Citizen\'s Original Request', hi: 'नागरिक का मूल अनुरोध', mr: 'नागरिकाची मूळ विनंती' },
  adminReport: { en: 'Admin Report / Action Taken', hi: 'प्रशासन रिपोर्ट / की गई कार्रवाई', mr: 'प्रशासन अहवाल / केलेली कारवाई' },
  uploadDocument: { en: 'Upload Document', hi: 'दस्तावेज अपलोड करें', mr: 'दस्तऐवज अपलोड करा' },
  finalize: { en: 'Finalize & Update', hi: 'अंतिम रूप दें और अपडेट करें', mr: 'अंतिम रूप द्या आणि अपडेट करा' },
  save: { en: 'Save', hi: 'सहेजें', mr: 'जतन करा' },
  updateStatus: { en: 'Update Status', hi: 'स्थिति अपडेट करें', mr: 'स्थिती अपडेट करा' },
  officialReport: { en: 'Official Report / Remarks', hi: 'आधिकारिक रिपोर्ट / टिप्पणी', mr: 'अधिकृत अहवाल / शेरा' },
  attachDocument: { en: 'Attach Official PDF/DOC', hi: 'आधिकारिक PDF/DOC संलग्न करें', mr: 'अधिकृत PDF/DOC जोडा' },
  finalizeResolution: { en: 'Finalize Resolution', hi: 'समाधान को अंतिम रूप दें', mr: 'निकालाला अंतिम रूप द्या' },
  version: { en: 'Version', hi: 'संस्करण', mr: 'आवृत्ती' },
  developedBy: { en: 'Developed by', hi: 'द्वारा विकसित', mr: 'द्वारे विकसित' },
  downloadApp: { en: 'Download App', hi: 'ऐप डाउनलोड करें', mr: 'अॅप डाउनलोड करा' },
  goToAppWeb: { en: 'Go to App Web', hi: 'ऐप वेब पर जाएं', mr: 'अॅप वेबवर जा' },
  shareApp: { en: 'Share App', hi: 'ऐप साझा करें', mr: 'अॅप शेअर करा' },
  contactSupport: { en: 'Contact for Support', hi: 'सहायता के लिए संपर्क करें', mr: 'मदतीसाठी संपर्क साधा' },
  empoweringRural: { en: 'Empowering rural communities through decentralized digital governance.', hi: 'विकेंद्रीकृत डिजिटल शासन के माध्यम से ग्रामीण समुदायों को सशक्त बनाना।', mr: 'विकेंद्रित डिजिटल शासनाद्वारे ग्रामीण समुदायांचे सक्षमीकरण.' },
  linkCopied: { en: 'Link copied to clipboard!', hi: 'लिंक क्लिपबोर्ड पर कॉपी की गई!', mr: 'लिंक क्लिपबोर्डवर कॉपी केली!' },
  certificatePortal: { en: 'Certificate Portal', hi: 'प्रमाणपत्र पोर्टल', mr: 'प्रमाणपत्र पोर्टल' },
  birth: { en: 'Birth', hi: 'जन्म', mr: 'जन्म' },
  death: { en: 'Death', hi: 'मृत्यु', mr: 'मृत्यू' },
  personFullName: { en: 'Full Name of Person', hi: 'व्यक्ति का पूरा नाम', mr: 'व्यक्तीचे पूर्ण नाव' },
  fatherFullName: { en: "Father's Name", hi: 'पिता का नाम', mr: 'वडिलांचे नाव' },
  motherFullName: { en: "Mother's Name", hi: 'माता का नाम', mr: 'आईचे नाव' },
  dob: { en: 'Date of Birth', hi: 'जन्म तिथि', mr: 'जन्मतारीख' },
  dod: { en: 'Date of Death', hi: 'मृत्यु तिथि', mr: 'मृत्यूची तारीख' },
  placeOfEvent: { en: 'Place of Event (Hospital/Home)', hi: 'घटना का स्थान (अस्पताल/घर)', mr: 'घटनेचे ठिकाण (रुग्णालय/घर)' },
  permanentAddress: { en: 'Permanent Address', hi: 'स्थायी पता', mr: 'कायमचा पत्ता' },
  submitRequest: { en: 'Submit Request', hi: 'अनुरोध जमा करें', mr: 'विनंती सादर करा' },
  nocPortal: { en: 'NOC Request Portal', hi: 'एनओसी अनुरोध पोर्टल', mr: 'ना हरकत दाखला पोर्टल' },
  selectNocCategory: { en: 'Select NOC Category', hi: 'एनओसी श्रेणी चुनें', mr: 'ना हरकत दाखला प्रवर्ग निवडा' },
  propertyGatNumber: { en: 'Property / Gat Number', hi: 'संपत्ति / गट नंबर', mr: 'मालमत्ता / गट नंबर' },
  applicantFullName: { en: 'Applicant Full Name', hi: 'आवेदक का पूरा नाम', mr: 'अर्जदाराचे पूर्ण नाव' },
  reasonPurpose: { en: 'Reason / Purpose', hi: 'कारण / उद्देश्य', mr: 'कारण / उद्देश' },
  propertyDocuments: { en: 'Property Documents (Aadhaar/Tax Receipt)', hi: 'संपत्ति दस्तावेज (आधार/टैक्स रसीद)', mr: 'मालमत्ता कागदपत्रे (आधार/कर पावती)' },
  uploadSupportingFile: { en: 'Upload Supporting File', hi: 'सहायक फाइल अपलोड करें', mr: 'सहायक फाईल अपलोड करा' },
  submitNocRequest: { en: 'Submit NOC Request', hi: 'एनओसी अनुरोध जमा करें', mr: 'ना हरकत दाखला विनंती सादर करा' },
  houseConstruction: { en: 'House Construction', hi: 'मकान निर्माण', mr: 'घर बांधकाम' },
  waterConnection: { en: 'Water Connection', hi: 'नल कनेक्शन', mr: 'नळ जोडणी' },
  electricityNoc: { en: 'Electricity NOC', hi: 'बिजली एनओसी', mr: 'वीज ना हरकत' },
  shopBusiness: { en: 'Shop/Business', hi: 'दुकान/व्यवसाय', mr: 'दुकान/व्यवसाय' },
  otherPurpose: { en: 'Other Purpose', hi: 'अन्य उद्देश्य', mr: 'इतर कारण' },
  satbara: { en: 'Satbara (7/12)', hi: 'सातबारा', mr: 'सातबारा' },
  eightA: { en: '8A Holding', hi: '8अ होल्डिंग', mr: '८अ उतारा' },
  ferfar: { en: 'Ferfar (Mutation)', hi: 'फेरफार', mr: 'फेरफार' },
  talathiRevenueDept: { en: 'This request will be processed by the Talathi / Revenue Department. You will receive a digital copy once verified.', hi: 'यह अनुरोध तलाठी / राजस्व विभाग द्वारा संसाधित किया जाएगा। सत्यापित होने के बाद आपको एक डिजिटल कॉपी प्राप्त होगी।', mr: 'ही विनंती तलाठी / महसूल विभागाद्वारे प्रक्रिया केली जाईल. पडताळणीनंतर तुम्हाला डिजिटल प्रत मिळेल.' },
  villageGaav: { en: 'Village (Gaav)', hi: 'गांव', mr: 'गाव' },
  khateNumber: { en: 'Khate Number (Account No)', hi: 'खाता नंबर', mr: 'खाते नंबर' },
  gatSurveyNumber: { en: 'Gat / Survey Number', hi: 'गट / सर्वे नंबर', mr: 'गट / सर्वे नंबर' },
  mutationType: { en: 'Mutation Type', hi: 'उत्परिवर्तन प्रकार', mr: 'फेरफार प्रकार' },
  detailsRemarks: { en: 'Details / Remarks', hi: 'विवरण / टिप्पणी', mr: 'तपशील / शेरा' },
  fullNameAsPerRecords: { en: 'Full Name (As per records)', hi: 'पूरा नाम (रिकॉर्ड के अनुसार)', mr: 'पूर्ण नाव (नोंदीनुसार)' },
  uploadIdOldDoc: { en: 'Upload ID or Old Document', hi: 'आईडी या पुराना दस्तावेज अपलोड करें', mr: 'ओळखपत्र किंवा जुने कागदपत्र अपलोड करा' },
  requestDocument: { en: 'Request Document', hi: 'दस्तावेज का अनुरोध करें', mr: 'कागदपत्रासाठी विनंती करा' },
  varasInheritance: { en: 'Varas (Inheritance)', hi: 'वारस (विरासत)', mr: 'वारस' },
  karediSaleDeed: { en: 'Karedi (Sale Deed)', hi: 'खरेदी खत', mr: 'खरेदी खत' },
  bakshisGift: { en: 'Bakshis (Gift)', hi: 'बक्षीस पत्र', mr: 'बक्षीस पत्र' },
  bogjaMortgage: { en: 'Bogja (Mortgage)', hi: 'बोजा (बंधक)', mr: 'बोजा' },
  watpDivision: { en: 'Watp (Division)', hi: 'वाटप (विभाजन)', mr: 'वाटप' },
  electricitySupport: { en: 'Electricity Support', hi: 'बिजली सहायता', mr: 'वीज मदत' },
  consumerNumber: { en: 'Consumer Number', hi: 'ग्राहक नंबर', mr: 'ग्राहक नंबर' },
  buCode: { en: 'BU Code (Billing Unit)', hi: 'बीयू कोड', mr: 'बीयू कोड' },
  problemCategory: { en: 'Problem Category', hi: 'समस्या श्रेणी', mr: 'समस्येचा प्रवर्ग' },
  contactMobile: { en: 'Contact Mobile', hi: 'संपर्क मोबाइल', mr: 'संपर्क मोबाईल' },
  submitComplaint: { en: 'Submit Complaint', hi: 'शिकायत दर्ज करें', mr: 'तक्रार नोंदवा' },
  billCorrection: { en: 'Bill Correction', hi: 'बिल सुधार', mr: 'बिल दुरुस्ती' },
  newMeterConnection: { en: 'New Meter Connection', hi: 'नया मीटर कनेक्शन', mr: 'नवीन मीटर जोडणी' },
  meterReplacement: { en: 'Meter Replacement', hi: 'मीटर बदलना', mr: 'मीटर बदलणे' },
  gasServiceHub: { en: 'Gas Service Hub', hi: 'गैस सेवा हब', mr: 'गॅस सेवा केंद्र' },
  lpgAgency: { en: 'LPG Agency', hi: 'एलपीजी एजेंसी', mr: 'एलपीजी एजन्सी' },
  consumerId: { en: 'Consumer ID', hi: 'उपभोक्ता आईडी', mr: 'ग्राहक आयडी' },
  consumerName: { en: 'Consumer Name', hi: 'उपभोक्ता का नाम', mr: 'ग्राहकाचे नाव' },
  fullAddress: { en: 'Full Address', hi: 'पूरा पता', mr: 'पूर्ण पत्ता' },
  idProofType: { en: 'ID Proof Type', hi: 'आईडी प्रूफ प्रकार', mr: 'ओळखपत्राचा प्रकार' },
  connectionType: { en: 'Connection Type', hi: 'कनेक्शन प्रकार', mr: 'जोडणीचा प्रकार' },
  serviceRequested: { en: 'Service Requested', hi: 'अनुरोधित सेवा', mr: 'विनंती केलेली सेवा' },
  refillBooking: { en: 'Refill Booking', hi: 'रिफिल बुकिंग', mr: 'रिफिल बुकिंग' },
  newGasConnection: { en: 'New Gas Connection', hi: 'नया गैस कनेक्शन', mr: 'नवीन गॅस जोडणी' },
  safetyCheckLeakage: { en: 'Safety Check / Leakage', hi: 'सुरक्षा जांच / रिसाव', mr: 'सुरक्षा तपासणी / गळती' },
  kycUpdate: { en: 'KYC Update', hi: 'केवाईसी अपडेट', mr: 'केवायसी अपडेट' },
  opdRegistration: { en: 'OPD Registration', hi: 'ओपीडी पंजीकरण', mr: 'ओपीडी नोंदणी' },
  phcRequestInfo: { en: 'Your request will be sent to the Primary Health Center (PHC). You will receive a confirmation message shortly.', hi: 'आपका अनुरोध प्राथमिक स्वास्थ्य केंद्र (PHC) को भेजा जाएगा। आपको जल्द ही एक पुष्टिकरण संदेश प्राप्त होगा।', mr: 'तुमची विनंती प्राथमिक आरोग्य केंद्राकडे (PHC) पाठवली जाईल. तुम्हाला लवकरच पुष्टीकरण संदेश मिळेल.' },
  patientFullName: { en: 'Patient Full Name', hi: 'मरीज का पूरा नाम', mr: 'रुग्णाचे पूर्ण नाव' },
  age: { en: 'Age', hi: 'आयु', mr: 'वय' },
  gender: { en: 'Gender', hi: 'लिंग', mr: 'लिंग' },
  symptomsReason: { en: 'Symptoms / Reason', hi: 'लक्षण / कारण', mr: 'लक्षणे / कारण' },
  preferredDate: { en: 'Preferred Date', hi: 'पसंदीदा तिथि', mr: 'पसंतीची तारीख' },
  submitHealthRequest: { en: 'Submit Health Request', hi: 'स्वास्थ्य अनुरोध जमा करें', mr: 'आरोग्य विनंती सादर करा' },
  male: { en: 'Male', hi: 'पुरुष', mr: 'पुरुष' },
  female: { en: 'Female', hi: 'महिला', mr: 'स्त्री' },
  other: { en: 'Other', hi: 'अन्य', mr: 'इतर' },
  issueDescription: { en: 'Description of issue', hi: 'समस्या का विवरण', mr: 'समस्येचे वर्णन' },
  helpDescriptionPlaceholder: { en: 'Tell us what you need help with...', hi: 'हमें बताएं कि आपको किस चीज में मदद चाहिए...', mr: 'तुम्हाला कशात मदत हवी आहे ते सांगा...' },
  avgResponseTime: { en: 'Average response time: 24-48 hours', hi: 'औसत प्रतिक्रिया समय: 24-48 घंटे', mr: 'सरासरी प्रतिसाद वेळ: २४-४८ तास' },
  sendHelpRequest: { en: 'Send Help Request', hi: 'सहायता अनुरोध भेजें', mr: 'मदत विनंती पाठवा' },
  officerAccessKey: { en: 'Officer Access Key', hi: 'अधिकारी एक्सेस की', mr: 'अधिकारी प्रवेश की' },
  enter8CharKey: { en: 'Enter 8-Character Key', hi: '8-अक्षर की कुंजी दर्ज करें', mr: '८-अक्षरी की प्रविष्ट करा' },
  pendingApproval: { en: 'Your account is pending approval from Grampanchayat. Please try again later.', hi: 'आपका खाता ग्रामपंचायत से अनुमोदन के लिए लंबित है। कृपया बाद में पुनः प्रयास करें।', mr: 'तुमचे खाते ग्रामपंचायतीकडून मंजुरीसाठी प्रलंबित आहे. कृपया नंतर पुन्हा प्रयत्न करा.' },
  rejectedApproval: { en: 'Your registration has been rejected. Please contact Grampanchayat.', hi: 'आपका पंजीकरण अस्वीकार कर दिया गया है। कृपया ग्रामपंचायत से संपर्क करें।', mr: 'तुमची नोंदणी नाकारली गेली आहे. कृपया ग्रामपंचायतीशी संपर्क साधा.' },
  regSuccessPending: { en: 'Registration successful! Your account is now pending approval from Grampanchayat.', hi: 'पंजीकरण सफल! आपका खाता अब ग्रामपंचायत से अनुमोदन के लिए लंबित है।', mr: 'नोंदणी यशस्वी! तुमचे खाते आता ग्रामपंचायतीकडून मंजुरीसाठी प्रलंबित आहे.' },
  myGaavTickets: { en: 'My Gaav Tickets', hi: 'मेरे गांव टिकट', mr: 'माझे गाव तिकीट' },
  newServiceRequest: { en: 'New Service Request', hi: 'नया सेवा अनुरोध', mr: 'नवीन सेवा विनंती' },
  explainIssue: { en: 'Explain your issue...', hi: 'अपनी समस्या बताएं...', mr: 'तुमची समस्या सांगा...' },
  officialTasksFromAdmin: { en: 'Official Tasks From Admin', hi: 'प्रशासन से आधिकारिक कार्य', mr: 'प्रशासनाकडून अधिकृत कामे' },
  myServiceRequests: { en: 'My Service Requests', hi: 'मेरे सेवा अनुरोध', mr: 'माझ्या सेवा विनंत्या' },
  noActiveRequests: { en: 'No active requests', hi: 'कोई सक्रिय अनुरोध नहीं', mr: 'कोणतीही सक्रिय विनंती नाही' },
  officialTask: { en: 'Official Task', hi: 'आधिकारिक कार्य', mr: 'अधिकृत काम' },
  officerResolutionReport: { en: 'Officer Resolution Report', hi: 'अधिकारी समाधान रिपोर्ट', mr: 'अधिकारी निकाल अहवाल' },
  officialDoc: { en: 'Official Doc', hi: 'आधिकारिक दस्तावेज', mr: 'अधिकृत दस्तऐवज' },
  confirmSatisfaction: { en: 'Confirm Satisfaction', hi: 'संतुष्टि की पुष्टि करें', mr: 'समाधानाची पुष्टी करा' },
  gaavTaxRecords: { en: 'Gaav Tax Records', hi: 'गांव टैक्स रिकॉर्ड', mr: 'गाव कर नोंदी' },
  taxCenterTitle: { en: 'Tax Center', hi: 'टैक्स सेंटर', mr: 'कर केंद्र' },
  taxCenterSub: { en: 'Pay your village taxes and dues', hi: 'अपने गांव के टैक्स और बकाया राशि का भुगतान करें', mr: 'तुमचे गावचे कर आणि थकबाकी भरा' },
  actionRequired: { en: 'Action Required', hi: 'कार्रवाई आवश्यक', mr: 'कृती आवश्यक' },
  totalPending: { en: 'Total Pending', hi: 'कुल लंबित', mr: 'एकूण प्रलंबित' },
  receiptNo: { en: 'Receipt No', hi: 'रसीद संख्या', mr: 'पावती क्रमांक' },
  transactionId: { en: 'Transaction ID', hi: 'लेनदेन आईडी', mr: 'व्यवहार आयडी' },
  paidOn: { en: 'Paid On', hi: 'भुगतान की तिथि', mr: 'पेमेंट तारीख' },
  issueDate: { en: 'Issue Date', hi: 'जारी करने की तिथि', mr: 'जारी तारीख' },
  dueDate: { en: 'Due Date', hi: 'नियत तिथि', mr: 'देय तारीख' },
  detailedRemarks: { en: 'Detailed Remarks', hi: 'विस्तृत टिप्पणी', mr: 'तपशीलवार शेरा' },
  receipt: { en: 'Receipt', hi: 'रसीद', mr: 'पावती' },
  pay: { en: 'Pay', hi: 'भुगतान करें', mr: 'पेमेंट करा' },
  completed: { en: 'Completed', hi: 'पूरा हुआ', mr: 'पूर्ण झाले' },
  grocery: { en: 'Grocery', hi: 'किराना', mr: 'किराणा' },
  salon: { en: 'Salon', hi: 'सैलून', mr: 'सलून' },
  medical: { en: 'Medical', hi: 'मेडिकल', mr: 'मेडिकल' },
  agriStore: { en: 'Agri-Store', hi: 'कृषि भंडार', mr: 'कृषी भांडार' },
  tailor: { en: 'Tailor', hi: 'दर्जी', mr: 'शिंपी' },
  dairy: { en: 'Dairy', hi: 'डेयरी', mr: 'डेअरी' },
  myProfile: { en: 'My Profile', hi: 'मेरी प्रोफाइल', mr: 'माझी प्रोफाइल' },
  email: { en: 'Email', hi: 'ईमेल', mr: 'ईमेल' },
  residentId: { en: 'Resident ID', hi: 'निवासी आईडी', mr: 'निवासी आयडी' },
  memberSince: { en: 'Member Since', hi: 'सदस्यता की तिथि', mr: 'सदस्यता तारीख' },
  digitalGaavPortal: { en: 'Digital Gaav Portal', hi: 'डिजिटल गांव पोर्टल', mr: 'डिजिटल गाव पोर्टल' }
};

export const SERVICES: ServiceInfo[] = [
  {
    id: ServiceType.GRAMPANCHAYAT,
    title: { en: "Gram Panchayat", hi: "ग्राम पंचायत", mr: "ग्रामपंचायत" },
    icon: "Building2",
    color: "bg-emerald-500",
    description: { en: "Governance & Administration", hi: "प्रशासन", mr: "प्रशासन" },
    details: [
      { en: "Birth/Death Certificates", hi: "जन्म/मृत्यु प्रमाणपत्र", mr: "जन्म/मृत्यू प्रमाणपत्र" },
      { en: "Property Taxes", hi: "संपत्ति कर", mr: "मालमत्ता कर" },
      { en: "NOC Requests", hi: "एनओसी अनुरोध", mr: "ना हरकत प्रमाणपत्र" }
    ]
  },
  {
    id: ServiceType.CHAVDI,
    title: { en: "E-Chavdi", hi: "ई-चावड़ी", mr: "ई-चावडी" },
    icon: "FileText",
    color: "bg-amber-500",
    description: { en: "Land Records Portal", hi: "भूमि रिकॉर्ड", mr: "जमिनीचे रेकॉर्ड" },
    details: [
      { en: "Satbara (7/12) Extract", hi: "सातबारा", mr: "सातबारा" },
      { en: "8A Holding", hi: "8अ होल्डिंग", mr: "८अ उतारा" },
      { en: "Ferfar (Mutation)", hi: "फेरफार", mr: "फेरफार" }
    ]
  },
  {
    id: ServiceType.BUSINESS,
    title: { en: "Local Directory", hi: "स्थानीय निर्देशिका", mr: "स्थानिक व्यवसाय" },
    icon: "Store",
    color: "bg-indigo-500",
    description: { en: "Village Business Directory", hi: "गांव व्यवसाय सूची", mr: "ग्राम व्यवसाय सूची" },
    details: [
      { en: "View Local Businesses", hi: "स्थानीय व्यवसाय देखें", mr: "स्थानिक व्यवसाय पहा" },
      { en: "Register My Service", hi: "मेरी सेवा पंजीकृत करें", mr: "माझी सेवा नोंदवा" }
    ]
  },
  {
    id: ServiceType.ELECTRICITY,
    title: { en: "Electricity", hi: "बिजली", mr: "वीज" },
    icon: "Zap",
    color: "bg-blue-500",
    description: { en: "Bill Payments & Issues", hi: "बिल और शिकायतें", mr: "बिल आणि तक्रारी" },
    details: [
      { en: "Pay Monthly Bill", hi: "मासिक बिल भरें", mr: "मासिक बिल भरा" }
    ]
  },
  {
    id: ServiceType.GAS,
    title: { en: "Gas Services", hi: "गैस सेवाएँ", mr: "गॅस सेवा" },
    icon: "Flame",
    color: "bg-orange-500",
    description: { en: "LPG Booking & Support", hi: "गैस बुकिंग", mr: "गॅस बुकिंग" },
    details: [
      { en: "Refill Booking", hi: "रीफिल बुकिंग", mr: "रीफिल बुकिंग" },
      { en: "New Connection", hi: "नया कनेक्शन", mr: "नवीन कनेक्शन" }
    ]
  },
  {
    id: ServiceType.HEALTH,
    title: { en: "Health Services", hi: "स्वास्थ्य सेवाएँ", mr: "आरोग्य सेवा" },
    icon: "HeartPulse",
    color: "bg-rose-500",
    description: { en: "Public Health & Wellness", hi: "जन स्वास्थ्य", mr: "सार्वजनिक आरोग्य" },
    details: [
      { en: "OPD Registration", hi: "ओपीडी पंजीकरण", mr: "ओपीडी नोंदणी" }
    ]
  }
];

export const getIcon = (iconName: string, size = 24, className = "") => {
  const icons: Record<string, React.ReactNode> = {
    Building2: <Building2 size={size} className={className} />,
    Zap: <Zap size={size} className={className} />,
    Flame: <Flame size={size} className={className} />,
    FileText: <FileText size={size} className={className} />,
    HeartPulse: <HeartPulse size={size} className={className} />,
    ShoppingBasket: <ShoppingBasket size={size} className={className} />,
    Bot: <Bot size={size} className={className} />,
    Store: <Store size={size} className={className} />
  };
  return icons[iconName] || null;
};
